# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Finished_Calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QApplication

class Ui_MainWindow(object):
    def __init__(self, window):
        super(Ui_MainWindow,self).__init__()
        self.start_op=False #operaciebis samartavi obieqti
        self.sia = []
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(80, 80, 80);\n"
"border-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 30, 431, 481))
        
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"font: 16pt \"MS Serif\";")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(20, 60, 291, 71))
        
        self.textBrowser.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setGeometry(QtCore.QRect(20, 140, 93, 71))
        self.pushButton_19.setAutoFillBackground(False)
        self.pushButton_19.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setGeometry(QtCore.QRect(120, 140, 93, 71))
        self.pushButton_20.setAutoFillBackground(False)
        self.pushButton_20.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_22.setGeometry(QtCore.QRect(220, 140, 93, 71))
        self.pushButton_22.setAutoFillBackground(False)
        self.pushButton_22.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_30.setGeometry(QtCore.QRect(320, 140, 93, 71))
        self.pushButton_30.setAutoFillBackground(False)
        self.pushButton_30.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_23.setGeometry(QtCore.QRect(120, 380, 93, 71))
        self.pushButton_23.setAutoFillBackground(False)
        self.pushButton_23.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_32.setGeometry(QtCore.QRect(320, 380, 93, 71))
        self.pushButton_32.setAutoFillBackground(False)
        self.pushButton_32.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_25.setGeometry(QtCore.QRect(220, 380, 93, 71))
        self.pushButton_25.setAutoFillBackground(False)
        self.pushButton_25.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 380, 93, 71))
        self.pushButton_26.setAutoFillBackground(False)
        self.pushButton_26.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_21.setGeometry(QtCore.QRect(120, 220, 93, 71))
        self.pushButton_21.setAutoFillBackground(False)
        self.pushButton_21.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_31.setGeometry(QtCore.QRect(320, 220, 93, 71))
        self.pushButton_31.setAutoFillBackground(False)
        self.pushButton_31.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_24.setGeometry(QtCore.QRect(220, 220, 93, 71))
        self.pushButton_24.setAutoFillBackground(False)
        self.pushButton_24.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_27.setGeometry(QtCore.QRect(20, 220, 93, 71))
        self.pushButton_27.setAutoFillBackground(False)
        self.pushButton_27.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_28.setGeometry(QtCore.QRect(220, 300, 93, 71))
        self.pushButton_28.setAutoFillBackground(False)
        self.pushButton_28.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_29.setGeometry(QtCore.QRect(120, 300, 93, 71))
        self.pushButton_29.setAutoFillBackground(False)
        self.pushButton_29.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_33.setGeometry(QtCore.QRect(20, 300, 93, 71))
        self.pushButton_33.setAutoFillBackground(False)
        self.pushButton_33.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_34.setGeometry(QtCore.QRect(320, 300, 93, 71))
        self.pushButton_34.setAutoFillBackground(False)
        self.pushButton_34.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_35.setGeometry(QtCore.QRect(320, 60, 93, 71))
        self.pushButton_35.setAutoFillBackground(False)
        self.pushButton_35.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.pushButton_35.setObjectName("pushButton_35")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

         
        self.pushButton_19.clicked.connect(lambda:self.clicked(self.pushButton_19.text())) # 7 
        self.pushButton_20.clicked.connect(lambda:self.clicked(self.pushButton_20.text())) # 8
        self.pushButton_21.clicked.connect(lambda:self.clicked(self.pushButton_21.text())) # 5
        self.pushButton_22.clicked.connect(lambda:self.clicked(self.pushButton_22.text())) # 9
        self.pushButton_23.clicked.connect(lambda:self.clicked(self.pushButton_23.text())) # 0
        self.pushButton_24.clicked.connect(lambda:self.clicked(self.pushButton_24.text())) # 6
        self.pushButton_27.clicked.connect(lambda:self.clicked(self.pushButton_27.text())) # 4
        self.pushButton_28.clicked.connect(lambda:self.clicked(self.pushButton_28.text())) # 3
        self.pushButton_29.clicked.connect(lambda:self.clicked(self.pushButton_29.text())) # 2
        self.pushButton_33.clicked.connect(lambda:self.clicked(self.pushButton_33.text())) # 1
        
        self.pushButton_30.clicked.connect(lambda:self.operation_concat(self.pushButton_30.text())) # /
        self.pushButton_25.clicked.connect(lambda:self.operation_concat(self.pushButton_25.text())) # =
        self.pushButton_32.clicked.connect(lambda:self.operation_concat(self.pushButton_32.text())) # +
        self.pushButton_31.clicked.connect(lambda:self.operation_concat(self.pushButton_31.text())) # *
        self.pushButton_34.clicked.connect(lambda:self.operation_concat(self.pushButton_34.text())) # -
        self.pushButton_35.clicked.connect(self.clear) # Clear
    # dawkapunebisas gaaqtiurdeba qveda funqcia
    def clicked(self,text): 
        self.textBrowser.setText(text)
    
    #operaciis mititebisas gaaqtiurdeba qveda funqcia romelic sheaertebs teqsts
    def operation_concat(self,text):
        self.start_op=True
        self.sia.append(self.textBrowser.text())
        self.textBrowser.append(text)
        
    def clear(self):
        self.textBrowser.clear()
       
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Time Machine Calculator"))
        self.pushButton_19.setText(_translate("MainWindow", "7"))
        self.pushButton_20.setText(_translate("MainWindow", "8"))
        self.pushButton_22.setText(_translate("MainWindow", "9"))
        self.pushButton_30.setText(_translate("MainWindow", "/"))
        self.pushButton_23.setText(_translate("MainWindow", "0"))
        self.pushButton_32.setText(_translate("MainWindow", "+"))
        self.pushButton_25.setText(_translate("MainWindow", "="))
        self.pushButton_26.setText(_translate("MainWindow", "."))
        self.pushButton_21.setText(_translate("MainWindow", "5"))
        self.pushButton_31.setText(_translate("MainWindow", "*"))
        self.pushButton_24.setText(_translate("MainWindow", "6"))
        self.pushButton_27.setText(_translate("MainWindow", "4"))
        self.pushButton_28.setText(_translate("MainWindow", "3"))
        self.pushButton_29.setText(_translate("MainWindow", "2"))
        self.pushButton_33.setText(_translate("MainWindow", "1"))
        self.pushButton_34.setText(_translate("MainWindow", "-"))
        self.pushButton_35.setText(_translate("MainWindow", "C"))
    
    
    

    
app = QApplication([]) #vqmnit aplikacias
window = QMainWindow() # samusashao fanjris obieqti
ui = Ui_MainWindow(window)  # qt disainerris obieqtis sheqmna
ui.setupUi(window) # chveni sheqmnili fanjris qt disaineris obieqtshi gadacema
window.show() #
app.exec_()